version: 2.1
executors:
    node-executor:
        docker:
            - image: circleci/node:10
        working_directory: ~/repo

commands:
    install_dep:
        description: 'Install the frontend dependencies using Yarn and cache them'

        steps:
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      # Find a cache corresponding to the specific yarn.lock checksum
                      # when this files is changed, this key will fail
                      - yarn-packages-{{ checksum "yarn.lock" }}
                      - yarn-packages-

            - run:
                  name: Install Dependencies
                  command: yarn install --frozen-lockfile

            - save_cache:
                  name: Save Yarn Package Cache
                  # Create a new cache key corresponding to this specific yarn.lock
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn

    run_react_tests:
        description: 'Run unit tests'

        steps:
            - run:
                  name: Run unit tests
                  command: |
                      yarn test
                  when: always

jobs:
    frontend-test:
        executor: node-executor
        steps:
            - checkout
            - install_dep
            - run_react_tests

workflows:
    version: 2.1
    tests:
        jobs:
            - frontend-test
